name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: "70.34.212.236"
          username: root
          password: ${{ secrets.VULTR_PASSWORD }}
          port: "22"
          strip_components: 1
          overwrite: true
          source: "src/"
          target: "/var/www/ostlund/"